# Local Makefile.def

localdefault: help # default target

SCRIPTDIR = ${DIR}/share/Scripts
LIBDIR    = ${DIR}/src
BINDIR    = ${DIR}/bin
SHAREDIR  = ${DIR}/share/Library/src
TIMINGDIR = ${DIR}/util/TIMING/src
