#^CFG FILE TESTING

### TESTS FOR STAND-ALONE BATSRUS ###

test: test_shocktube test_titan test_func
	ls -l *.diff

# All tests are done in this directory:
TESTDIR = run_test

# Reference solution is put into this directory when needed:
REFDIR = run_test_ref

# Tests are done either parallel or serial. Default:
MPIRUN = mpirun -np 2

test_help:
	@echo "    test                       (run all tests with ${MPIRUN})"
	@echo "    test MPIRUN=               (run all tests serially)"
	@echo "    test MPIRUN='mpirun -np 3' (run test with mpirun -np 3)"
	@echo "    test MPIRUN='mprun -np 2'  (run test with mprun -np 2)"
	@echo "    test_shocktube             (run shocktube test only)"
	@echo "    test_titan                 (run titan tests only)"
	@echo "    test_titan_start           (run first titan test only)"
	@echo "    test_titan_restart         (run titan restart test only)"
	@echo "    test_func                  (run functionality tests only)"

test_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR} STANDALONE=GM GMDIR=`pwd`


### SHOCK TUBE TEST ###

test_shocktube:
	@echo "test_shocktube_compile..." > test_shocktube.diff
	make test_shocktube_compile
	@echo "test_shocktube_rundir..." >> test_shocktube.diff
	make test_shocktube_rundir
	@echo "test_shocktube_run..." >> test_shocktube.diff
	make test_shocktube_run
	@echo "test_shocktube_check..." >> test_shocktube.diff
	make test_shocktube_check

test_shocktube_compile:
	make clean
	./Config.pl -u=Default -e=Mhd -g=256,4,4,10,1
	make
	make PIDL

test_shocktube_rundir: test_rundir
	cd ${TESTDIR}; cp GM/Param/SHOCKTUBE/PARAM.in .

test_shocktube_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog

test_shocktube_check:
	cat ${TESTDIR}/GM/IO2/cut_raw_2_t00000025_n0000358_pe*.idl \
		> ${TESTDIR}/GM/IO2/cut_25.idl
	${SCRIPTDIR}/DiffNum.pl -t -a=1e-15 \
	  Param/SHOCKTUBE/TestOutput/cut_raw_2_t00000025_n0000358_pe0000.idl \
	  ${TESTDIR}/GM/IO2/cut_25.idl > test_shocktube.diff
	ls -l test_shocktube.diff

### FUNCTIONALITY TEST SUITE ###

test_func:
	@echo "test_func_compile..." > test_func.diff
	make test_func_compile
	@echo "test_func_run..." >> test_func.diff
	make test_func_run
	@echo "test_func_check..." >> test_func.diff
	make test_func_check

test_func_compile:
	make clean
	./Config.pl -u=Default -e=Mhd -g=8,8,8,720,40
	make BATSRUS PIDL PSPH

test_func_run: test_rundir
	./TestSuite.pl -r='${MPIRUN} ' -d=${TESTDIR} func

test_func_check:
	rm -rf ${REFDIR}; mkdir ${REFDIR}
	cd ${REFDIR}; tar -xzf ../Param/TESTSUITE/TEST.tgz; 
	./TestCompare.pl -q -v -o=1e-8 ${REFDIR} ${TESTDIR} > test_func.diff
	./TestCompare.pl -speed ${REFDIR} ${TESTDIR} > test_func.speed
	ls -l test_func.diff test_func.speed

### TESTS FOR MODELING TITAN ###

test_titan:
	-@(make test_titan_start)
	-@(make test_titan_restart)

test_titan_start:
	@echo "test_titan_compile..." > test_titan.diff
	make test_titan_compile
	@echo "test_titan_rundir..." >> test_titan.diff
	make test_titan_rundir
	@echo "test_titan_run..." >> test_titan.diff
	make test_titan_run
	@echo "test_titan_check..." >> test_titan.diff
	make test_titan_check

test_titan_compile:
	make clean
	./Config.pl -u=Titan -e=MhdTitan -g=4,4,4,2000,200
	make
	make PIDL

test_titan_rundir: test_rundir
	cd ${TESTDIR}; \
		cp GM/Param/TITAN/PARAM.in .; \
		tar xzf GM/Param/TITAN/TitanInput.tgz
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_titan_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf TitanTest
	cd ${TESTDIR}; ./PostProc.pl -M -o TitanTest

test_titan_check:
	${SCRIPTDIR}/DiffNum.pl -t -a=1e-15 \
		Param/TITAN/TestOutput/log_n000001.log \
		${TESTDIR}/TitanTest/GM/log_n000001.log > test_titan.diff
	ls -l test_titan.diff

test_titan_restart:
	@echo "test_titan_restart_save..." > test_titan_restart.diff
	make test_titan_restart_save
	@echo "test_titan_restart_read..." >> test_titan_restart.diff
	make test_titan_restart_read
	@echo "test_titan_restart_check..." >> test_titan_restart.diff
	make test_titan_restart_check

test_titan_restart_save:
	cd ${TESTDIR}; cp GM/Param/TITAN/PARAM.in.restartsave PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf TitanTest/RestartSave RESTART_titan
	cd ${TESTDIR}; ./PostProc.pl -M -o TitanTest/RestartSave
	cd ${TESTDIR}; ./Restart.pl -o RESTART_titan; 

test_titan_restart_read:
	cd ${TESTDIR}; cp GM/Param/TITAN/PARAM.in.restartread PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ./Restart.pl -i RESTART_titan
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf TitanTest/RestartRead
	cd ${TESTDIR}; ./PostProc.pl -M -o TitanTest/RestartRead

test_titan_restart_check:
	cd ${TESTDIR}/TitanTest; \
		cp RestartSave/GM/log_n000001.log log_all.log; \
		tail -25 RestartRead/GM/log_n000026.log >> log_all.log
	${SCRIPTDIR}/DiffNum.pl -t -a=1e-15 \
		Param/TITAN/TestOutput/log_n000001.log \
		${TESTDIR}/TitanTest/log_all.log > test_titan_restart.diff
	ls -l test_titan*.diff
