#^CFG FILE TESTING

### TESTS FOR THE STAND-ALONE BATSRUS ###

# !!! NOTE: In the list below "test_func" should be the last test
test: 
	@rm -f *.diff
	-@(make test_fluxemergence)
	-@(make test_shocktube)
	-@(make test_hallmhd)
	-@(make test_twofluidmhd)
	-@(make test_multifluid)
	-@(make test_multiion)
	-@(make test_mhdions)
	-@(make test_mhdnoncons)
	-@(make test_eosgodunov)
	-@(make test_levelset)
	-@(make test_hyades2d)
	-@(make test_graydiffusion)
	-@(make test_corona)
	-@(make test_coronasph)
	-@(make test_outerhelio)
	-@(make test_earthsph)
	-@(make test_2bodyplot)
	-@(make test_titan)
	-@(make test_mars)
	-@(make test_marsfluids)
	-@(make test_venus)
	-@(make test_saturn)
	-@(make test_comet)
	-@(make test_magnetometer)
	-@(make test_anisotropic)
	-@(make test_func)
	@ls -l *.diff

# !!! NOTE: In the above list "test_func" should be the last test

# All tests are done in this directory:
TESTDIR = run_test

# Reference solution is put into this directory when needed:
REFDIR = run_test_ref

# Tests are done either parallel or serial. Default:
MPIRUN = mpirun -np 2

test_help:
	@echo "    test                       (run all tests with ${MPIRUN})"
	@echo "    test MPIRUN=               (run all tests serially)"
	@echo "    test MPIRUN='mpirun -np 3' (run test with mpirun -np 3)"
	@echo "    test MPIRUN='mprun -np 2'  (run test with mprun -np 2)"
	@echo "    test_anisotropic           (run anisotropic pressure test)"
	@echo "    test_2bodyplot             (run 2 Body Plot test)"
	@echo "    test_comet                 (run comet test)"
	@echo "    test_corona                (run Solar Corona test)"
	@echo "    test_coronasph             (run spherical Solar Corona test)"
	@echo "    test_earthsph              (run spherical Earth test)"
	@echo "    test_eosgodunov            (run EOS/Godunov test)"
	@echo "    test_fluxemergence         (run flux emergence test)"
	@echo "    test_func                  (run functionality tests)"
	@echo "    test_graydiffusion         (run gray-diffusion set test)"
	@echo "    test_hallmhd               (run Hall MHD test)"
	@echo "    test_hyades2d              (run Hyades2D test)"
	@echo "    test_levelset              (run levelset test)"
	@echo "    test_magnetometer          (run magnetometer test)"
	@echo "    test_mars                  (run Mars test)"
	@echo "    test_marsfluids            (run marsfluids tests)"
	@echo "    test_marsfluids_start      (run first marsfluids test)"
	@echo "    test_marsfluids_restart    (run marsfluids restart test)"
	@echo "    test_mhdions               (run MHD with ions test)"
	@echo "    test_mhdnoncons            (run non-conservative MHD test)"
	@echo "    test_multifluid            (run multi-fluid test)"
	@echo "    test_multiion              (run multi-ion test)"
	@echo "    test_outerhelio            (run Outer Heliosphere test)"
	@echo "    test_saturn                (run Saturn test)"
	@echo "    test_shocktube             (run shocktube test)"
	@echo "    test_titan                 (run Titan tests)"
	@echo "    test_titan_start           (run first Titan test)"
	@echo "    test_titan_restart         (run titan restart test)"
	@echo "    test_twofluidmhd           (run two-fluid test)"
	@echo "    test_venus                 (run Venus test)"

test_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR} STANDALONE=YES GMDIR=`pwd`

### FLUX EMERGENCE TEST ###

test_fluxemergence:
	@echo "test_fluxemergence_compile..." > test_fluxemergence.diff
	make test_fluxemergence_compile
	@echo "test_fluxemergence_rundir..." >> test_fluxemergence.diff
	make test_fluxemergence_rundir 
	@echo "test_fluxemergence_run..." >> test_fluxemergence.diff
	make test_fluxemergence_run
	@echo "test_fluxemergence_check..." >> test_fluxemergence.diff
	make test_fluxemergence_check

test_fluxemergence_compile:
	./Config.pl -e=MhdEosRad -u=Ee -g=8,8,8,500,1
	make
	make PIDL

test_fluxemergence_rundir: test_rundir
	cd ${TESTDIR}; cp ../data/FLUXEMERGENCE/*.dat* .
	cd ${TESTDIR}; cp Param/FLUXEMERGENCE/Grid.* .
	cd ${TESTDIR}; gunzip *.gz

test_fluxemergence_run:
	cd ${TESTDIR}; cp Param/FLUXEMERGENCE/PARAM.in.FluxEmergence.1D PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog_1d
	cd ${TESTDIR}; ./PostProc.pl -M -cat RESULTS/run_1d
	cd ${TESTDIR}; cp Param/FLUXEMERGENCE/PARAM.in.FluxEmergence.3D PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog_3d
	cd ${TESTDIR}; ./Restart.pl
	cd ${TESTDIR}; ./PostProc.pl -M -cat RESULTS/run_3d
	cd ${TESTDIR}; cp Param/FLUXEMERGENCE/PARAM.in.FluxEmergence PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog_restart
	cd ${TESTDIR}; ./PostProc.pl -M -cat RESULTS/run_restart; mv runlog_restart RESULTS/run_restart

test_fluxemergence_check:	
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-4 -a=2e-4 \
		Param/FLUXEMERGENCE/TestOutput/log_fluxemergence.log \
		${TESTDIR}/RESULTS/run_restart/GM/log_n000051.log > test_fluxemergence.diff
	ls -l test_fluxemergence.diff

### SHOCK TUBE TEST ###

test_shocktube:
	@echo "test_shocktube_compile..." > test_shocktube.diff
	make test_shocktube_compile
	@echo "test_shocktube_rundir..." >> test_shocktube.diff
	make test_shocktube_rundir
	@echo "test_shocktube_run..." >> test_shocktube.diff
	make test_shocktube_run
	@echo "test_shocktube_check..." >> test_shocktube.diff
	make test_shocktube_check

test_shocktube_compile:
	./Config.pl -u=Default -e=MhdHyp -g=256,4,4,10,1
	make
	make PIDL

test_shocktube_rundir: test_rundir
	cd ${TESTDIR}; cp Param/SHOCKTUBE/PARAM.in.hyp PARAM.in

test_shocktube_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog

test_shocktube_check:
	cat ${TESTDIR}/GM/IO2/cut_raw_2_t25.60000_n0000386_pe*.idl \
		> ${TESTDIR}/GM/IO2/cut_25.idl
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-13 \
	  Param/SHOCKTUBE/TestOutput/cut_25.idl \
	  ${TESTDIR}/GM/IO2/cut_25.idl > test_shocktube.diff
	ls -l test_shocktube.diff

### HALL MHD TEST ###

test_hallmhd:
	@echo "test_hallmhd_compile..." > test_hallmhd.diff
	make test_hallmhd_compile
	@echo "test_hallmhd_rundir..." >> test_hallmhd.diff
	make test_hallmhd_rundir
	@echo "test_hallmhd_run..." >> test_hallmhd.diff
	make test_hallmhd_run
	@echo "test_hallmhd_check..." >> test_hallmhd.diff
	make test_hallmhd_check

test_hallmhd_compile:
	./Config.pl -u=Waves -e=Mhd -g=64,2,2,10,10
	make
	make PIDL

test_hallmhd_rundir: test_rundir
	cd ${TESTDIR}; cp Param/SHOCKTUBE/PARAM.in.HallTest PARAM.in

test_hallmhd_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULT

test_hallmhd_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=2e-7 \
	  Param/SHOCKTUBE/TestOutput/hall_ref.out \
	  ${TESTDIR}/RESULT/GM/cut_*0118.out > test_hallmhd.diff
	ls -l test_hallmhd.diff

### TWOFLUID MHD TEST ###

test_twofluidmhd:
	@echo "test_twofluidmhd_compile..." > test_twofluidmhd.diff
	make test_twofluidmhd_compile
	@echo "test_twofluidmhd_rundir..." >> test_twofluidmhd.diff
	make test_twofluidmhd_rundir
	@echo "test_twofluidmhd_run..." >> test_twofluidmhd.diff
	make test_twofluidmhd_run
	@echo "test_twofluidmhd_check..." >> test_twofluidmhd.diff
	make test_twofluidmhd_check

test_twofluidmhd_compile:
	./Config.pl -u=Waves -e=MhdHypPe -g=64,2,2,10,10
	make
	make PIDL

test_twofluidmhd_rundir: test_rundir
	cd ${TESTDIR}; cp Param/SHOCKTUBE/PARAM.in.TwofluidTest PARAM.in

test_twofluidmhd_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULT

test_twofluidmhd_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-13 \
	  Param/SHOCKTUBE/TestOutput/twofluid_ref.out \
	  ${TESTDIR}/RESULT/GM/cut_mhd_1_t00000020*.out > test_twofluidmhd.diff
	ls -l test_twofluidmhd.diff

### MULTI FLUID TEST ###

test_multifluid:
	@echo "test_multifluid_compile..." > test_multifluid.diff
	make test_multifluid_compile
	@echo "test_multifluid_rundir..." >> test_multifluid.diff
	make test_multifluid_rundir
	@echo "test_multifluid_run..." >> test_multifluid.diff
	make test_multifluid_run
	@echo "test_multifluid_check..." >> test_multifluid.diff
	make test_multifluid_check

test_multifluid_compile:
	./Config.pl -u=Default -e=MhdHd -g=256,4,4,10,1
	make
	make PIDL

test_multifluid_rundir: test_rundir
	cd ${TESTDIR}; cp Param/MULTIFLUID/PARAM.in .

test_multifluid_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog

test_multifluid_check:
	@echo 'Brio and Sod tests' > ${TESTDIR}/GM/IO2/cut_25.idl
	@echo 'dx x y z Rho Mx My Mz Bx By Bz e NeuRho NeuMx NeuMy NeuMz NeuE p b1x b1y b1z' >> ${TESTDIR}/GM/IO2/cut_25.idl
	cat ${TESTDIR}/GM/IO2/cut_raw_2_t00000025_n*_pe*.idl \
		>> ${TESTDIR}/GM/IO2/cut_25.idl
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-12 \
	  Param/MULTIFLUID/TestOutput/cut_25.idl \
	  ${TESTDIR}/GM/IO2/cut_25.idl > test_multifluid.diff
	ls -l test_multifluid.diff

### TEST MAGNETOMETER ###
test_magnetometer:
	@echo "test_magnetometer_compile..." >> test_magnetometer.diff
	make test_magnetometer_compile
	@echo "test_magnetometer_rundir..." >> test_magnetometer.diff
	make test_magnetometer_rundir
	@echo "test_magnetometer_run..." >> test_magnetometer.diff
	make test_magnetometer_run
	@echo "test_magnetometer_check..." >> test_magnetometer.diff
	make test_magnetometer_check

test_magnetometer_compile:
	./Config.pl -u=Default -e=Mhd -g=4,4,4,400,1
	make
	make PIDL
	
test_magnetometer_rundir: test_rundir
	cd ${TESTDIR}; cp Param/MAGNETOMETER/PARAM.in PARAM.in
	cd ${TESTDIR}; cp Param/MAGNETOMETER/magin.dat .
	
test_magnetometer_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test_magnetometer_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-12 \
		Param/MAGNETOMETER/TestOutput/mag_n000000.dat \
		${TESTDIR}/RESULTS/GM/mag_n000000.dat \
		> test_magnetometer.diff	
	ls -l test_magnetometer.diff

### MULTI ION TEST ###

test_multiion:
	@echo "test_multiion_compile..." > test_multiion.diff
	make test_multiion_compile
	@echo "test_multiion_rundir..." >> test_multiion.diff
	make test_multiion_rundir
	@echo "test_multiion_run..." >> test_multiion.diff
	make test_multiion_run
	@echo "test_multiion_check..." >> test_multiion.diff
	make test_multiion_check

test_multiion_compile:
	./Config.pl -u=Default -e=MultiIon -g=64,2,2,10,1
	make
	make PIDL

test_multiion_rundir: test_rundir
	cd ${TESTDIR}; cp Param/MULTIION/PARAM.in .

test_multiion_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULTS

test_multiion_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-12 \
		Param/MULTIION/TestOutput/cut_t2.out \
		${TESTDIR}/RESULTS/GM/cut_*t02.*.out > test_multiion.diff
	ls -l test_multiion.diff

### MHD WITH MULTIPLE IONS TEST ###

test_mhdions:
	@echo "test_mhdions_compile..." > test_mhdions.diff
	make test_mhdions_compile
	@echo "test_mhdions_rundir..." >> test_mhdions.diff
	make test_mhdions_rundir
	@echo "test_mhdions_run..." >> test_mhdions.diff
	make test_mhdions_run
	@echo "test_mhdions_check..." >> test_mhdions.diff
	make test_mhdions_check

test_mhdions_compile:
	./Config.pl -u=Default -e=MhdIons -g=64,2,2,40,1
	make
	make PIDL

test_mhdions_rundir: test_rundir
	cd ${TESTDIR}; cp Param/MHDIONS/PARAM.in .

test_mhdions_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULTS

test_mhdions_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-11 \
		Param/MHDIONS/TestOutput/cut_mhd_t10m.out \
		${TESTDIR}/RESULTS/GM/cut_mhd_1_t00001000*.out \
		> test_mhdions.diff
	ls -l test_mhdions.diff

### NONCONSERVATIVE MHD TEST ###

test_mhdnoncons:
	@echo "test_mhdnoncons_compile..." > test_mhdnoncons.diff
	make test_mhdnoncons_compile
	@echo "test_mhdnoncons_rundir..." >> test_mhdnoncons.diff
	make test_mhdnoncons_rundir
	@echo "test_mhdnoncons_run..." >> test_mhdnoncons.diff
	make test_mhdnoncons_run
	@echo "test_mhdnoncons_check..." >> test_mhdnoncons.diff
	make test_mhdnoncons_check

test_mhdnoncons_compile:
	./Config.pl -u=Default -e=MhdNonCons -g=64,2,2,40,1
	make
	make PIDL

test_mhdnoncons_rundir: test_rundir
	cd ${TESTDIR}; cp Param/MHDNONCONS/PARAM.in .

test_mhdnoncons_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULTS

test_mhdnoncons_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-11 \
		Param/MHDNONCONS/TestOutput/cut_mhd_t10m.out \
		${TESTDIR}/RESULTS/GM/cut_mhd_1_t00001000*.out \
		> test_mhdnoncons.diff
	ls -l test_mhdnoncons.diff

### CRASH RELATED TESTS ###############################################

### EQUATION OF STATE AND GODUNOV SOLVER TEST ###

test_eosgodunov:
	@echo "test_eosgodunov_compile..." > test_eosgodunov.diff
	make test_eosgodunov_compile
	@echo "test_eosgodunov_rundir..." >> test_eosgodunov.diff
	make test_eosgodunov_rundir
	@echo "test_eosgodunov_run..." >> test_eosgodunov.diff
	make test_eosgodunov_run
	@echo "test_eosgodunov_check..." >> test_eosgodunov.diff
	make test_eosgodunov_check

test_eosgodunov_compile:
	./Config.pl -e=HdEos -u=Eos -g=10,1,1,100,1
	make CRASH
	make PIDL

test_eosgodunov_rundir: test_rundir
	cd ${TESTDIR}; cp Param/CRASH/PARAM.in.eosgodunov PARAM.in; \
	ln -s ${BINDIR}/CRASH.exe . 

test_eosgodunov_run:
	cd ${TESTDIR}; ${MPIRUN} ./CRASH.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULT

test_eosgodunov_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=3e-7 \
	  Param/CRASH/TestOutput/eosgodunov.out \
	  ${TESTDIR}/RESULT/GM/cut_*500.0*.out > test_eosgodunov.diff
	ls -l test_eosgodunov.diff

### LEVELSET TEST ###

test_levelset:
	@echo "test_levelset_compile..." > test_levelset.diff
	make test_levelset_compile
	@echo "test_levelset_rundir..." >> test_levelset.diff
	make test_levelset_rundir DEFAULT_EXE=CRASH.exe
	@echo "test_levelset_run..." >> test_levelset.diff
	make test_levelset_run
	@echo "test_levelset_check..." >> test_levelset.diff
	make test_levelset_check

test_levelset_compile:
	./Config.pl -e=HdCrash -u=Crash -g=4,4,1,2000,1
	make CRASH
	make PIDL

test_levelset_rundir: test_rundir
	cd ${TESTDIR}; cp Param/CRASH/PARAM.in.levelset PARAM.in
	cp dataCRASH/input/hyades_1.1ns.out ${TESTDIR}

test_levelset_run:
	cd ${TESTDIR}; ${MPIRUN} ./CRASH.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test_levelset_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=3e-7 \
		Param/CRASH/TestOutput/log_levelset.log \
		${TESTDIR}/RESULTS/GM/log_n000000.log > test_levelset.diff
	ls -l test_levelset.diff

### HYADES2D TEST ###

test_hyades2d:
	@echo "test_hyades2d_compile..." > test_hyades2d.diff
	make test_hyades2d_compile
	@echo "test_hyades2d_rundir..." >> test_hyades2d.diff
	make test_hyades2d_rundir DEFAULT_EXE=CRASH.exe
	@echo "test_hyades2d_run..." >> test_hyades2d.diff
	make test_hyades2d_run
	@echo "test_hyades2d_restart..." >> test_hyades2d.diff
	make test_hyades2d_restart
	@echo "test_hyades2d_check..." >> test_hyades2d.diff
	make test_hyades2d_check

test_hyades2d_compile:
	./Config.pl -e=HdRadCrash -u=Crash -g=10,10,1,200,200
	make CRASH
	make PIDL

test_hyades2d_rundir: test_rundir
	cd ${TESTDIR}; cp Param/CRASH/PARAM.in.hyades2d PARAM.in
	gunzip -c dataCRASH/input/hyades2d_1.1ns.out.gz \
		> ${TESTDIR}/hyades2d_1.1ns.out
	gunzip -c dataCRASH/input/opacities.out.gz \
	        > ${TESTDIR}/table_opacities.out

test_hyades2d_run:
	cd ${TESTDIR}; ${MPIRUN} ./CRASH.exe > runlog
	cd ${TESTDIR}; ./Restart.pl

test_hyades2d_restart:
	cd ${TESTDIR}; cp Param/CRASH/PARAM.in.hyades2d.restart PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./CRASH.exe > runlog_restart
	cd ${TESTDIR}; ./PostProc.pl -M -cat RESULTS; mv runlog_restart RESULTS

test_hyades2d_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-4 -a=1e-8 \
		Param/CRASH/TestOutput/log_hyades2d.log \
		${TESTDIR}/RESULTS/GM/log_n000000.log > test_hyades2d.diff
	ls -l test_hyades2d.diff

### MIXED CELL TEST ###

test_mixedcell:
	@echo "test_mixedcell_compile..." > test_mixedcell.diff
	make test_mixedcell_compile
	@echo "test_mixedcell_rundir..." >> test_mixedcell.diff
	make test_mixedcell_rundir DEFAULT_EXE=CRASH.exe
	@echo "test_mixedcell_run..." >> test_mixedcell.diff
	make test_mixedcell_run
	@echo "test_mixedcell_check..." >> test_mixedcell.diff
	make test_mixedcell_check

test_mixedcell_compile:
	./Config.pl -e=HdCrash -u=Crash -g=4,4,2,2000,1
	make CRASH
	make PIDL

test_mixedcell_rundir: test_rundir
	cd ${TESTDIR}; cp Param/CRASH/PARAM.in.mixedcell PARAM.in

test_mixedcell_run:
	cd ${TESTDIR}; ${MPIRUN} ./CRASH.exe > runlog
	cat ${TESTDIR}/GM/IO2/cut_hd_1_*_n0000882_pe*.idl \
		> ${TESTDIR}/IO2/cut_400_ns.idl
	#cd ${TESTDIR}; ./PostProc.pl -M

test_mixedcell_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=3e-7 \
		Param/CRASH/TestOutput/cut_mixedcell.idl \
		${TESTDIR}/IO2/cut_400_ns.idl > test_mixedcell.diff
	ls -l test_mixedcell.diff

### GRAY-DIFFUSION TEST ###

test_graydiffusion:
	@echo "test_graydiffusion_compile..." > test_graydiffusion.diff
	make test_graydiffusion_compile
	@echo "test_graydiffusion_rundir..." >> test_graydiffusion.diff
	make test_graydiffusion_rundir
	@echo "test_graydiffusion_run..." >> test_graydiffusion.diff
	make test_graydiffusion_run
	@echo "test_graydiffusion_check..." >> test_graydiffusion.diff
	make test_graydiffusion_check

test_graydiffusion_compile:
	./Config.pl -e=HdEosRad -u=GrayDiffusion -g=32,4,4,16,16
	make BATSRUS
	make PIDL

test_graydiffusion_rundir: test_rundir
	cd ${TESTDIR}; cp Param/CRASH/PARAM.in.graydiffusion PARAM.in
	cd ${TESTDIR}; cp Param/CRASH/initial_lowrie3.dat .

test_graydiffusion_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test_graydiffusion_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-4 \
		Param/CRASH/TestOutput/log_graydiffusion.log \
		${TESTDIR}/RESULTS/GM/log_n000000.log > test_graydiffusion.diff
	ls -l test_graydiffusion.diff

### END OF CRASH RELATED TESTS #############################################

### STANDALONE SOLAR CORONA TESTS ###

test_corona:
	@echo "test_corona_compile..." > test_corona.diff
	make test_corona_compile
	@echo "test_corona_rundir..." >> test_corona.diff
	make test_corona_rundir
	@echo "test_corona_run..." >> test_corona.diff
	make test_corona_run
	@echo "test_corona_check..." >> test_corona.diff
	make test_corona_check

test_corona_compile:
	./Config.pl -u=Sc -e=MhdCorona -g=4,4,4,3000,1
	make BATSRUS PIDL

test_corona_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR} COMPONENT=SC STANDALONE=YES GMDIR=`pwd`
	cd ${TESTDIR}; cp Param/CORONA/PARAM.in .
	cd ${TESTDIR}; cp Param/CORONA/CR1935_WSO.dat .

test_corona_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf RESULTS; ./PostProc.pl -M RESULTS

test_corona_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 \
		Param/CORONA/TestOutput/log_n000001.log \
		${TESTDIR}/RESULTS/SC/log_n000001.log > test_corona.diff
	ls -l test_corona.diff

# TEST SPHERICAL GRID FOR CORONA

test_coronasph:
	@echo "test_coronasph_compile..." > test_coronasph.diff
	make test_coronasph_compile
	@echo "test_coronasph_rundir..." >> test_coronasph.diff
	make test_coronasph_rundir
	@echo "test_coronasph_run..." >> test_coronasph.diff
	make test_coronasph_run
	@echo "test_coronasph_check..." >> test_coronasph.diff
	make test_coronasph_check

test_coronasph_compile:
	./Config.pl -u=Sc -e=MhdCorona -g=4,4,4,3000,1
	make BATSRUS PIDL

test_coronasph_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR} COMPONENT=SC STANDALONE=YES GMDIR=`pwd`
	cd ${TESTDIR}; cp Param/CORONA/PARAM.in.spherical PARAM.in
	cd ${TESTDIR}; cp Param/CORONA/CR1935_WSO.dat .

test_coronasph_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf RESULTS; ./PostProc.pl -M RESULTS

test_coronasph_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 \
		Param/CORONA/TestOutput/log_n000001.sph \
		${TESTDIR}/RESULTS/SC/log_n000001.log > test_coronasph.diff
	ls -l test_coronasph.diff

### STANDALONE OUTER HELIOSPHERE TESTS ###

test_outerhelio:
	@echo "test_outerhelio_compile..." > test_outerhelio.diff
	make test_outerhelio_compile
	@echo "test_outerhelio_rundir..." >> test_outerhelio.diff
	make test_outerhelio_rundir
	@echo "test_outerhelio_run..." >> test_outerhelio.diff
	make test_outerhelio_run
	@echo "test_outerhelio_check..." >> test_outerhelio.diff
	make test_outerhelio_check

test_outerhelio_compile:
	./Config.pl -u=OuterHelio -e=OuterHelio -g=4,4,4,3500,1
	make BATSRUS PIDL

test_outerhelio_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR} COMPONENT=OH STANDALONE=YES GMDIR=`pwd`
	cd ${TESTDIR}; cp Param/OUTERHELIO/PARAM.in .

test_outerhelio_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf RESULTS; ./PostProc.pl -M RESULTS

test_outerhelio_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 \
		Param/OUTERHELIO/TestOutput/log_n000000.log \
		${TESTDIR}/RESULTS/OH/log_n000000.log > test_outerhelio.diff
	ls -l test_outerhelio.diff

### FUNCTIONALITY TEST SUITE ###

test_func:
	@echo "test_func_compile..." > test_func.diff
	make test_func_compile
	@echo "test_func_run..." >> test_func.diff
	make test_func_run
	@echo "test_func_check..." >> test_func.diff
	make test_func_check

test_func_compile:
	./Config.pl -u=Default -e=Mhd -g=8,8,8,720,70
	make BATSRUS PIDL PSPH

test_func_run: test_rundir
	./TestSuite.pl -r='${MPIRUN} ' -d=${TESTDIR} func

test_func_check:
	rm -rf ${REFDIR}; mkdir ${REFDIR}
	cd ${REFDIR}; tar -xzf ../Param/TESTSUITE/TEST.tgz; 
	./TestCompare.pl -q -v -o=1e-11 ${REFDIR} ${TESTDIR} > test_func.diff
	./TestCompare.pl -speed ${REFDIR} ${TESTDIR} > test_func.speed
	ls -l test_func.diff test_func.speed

### TESTS FOR MODELING TITAN ###

test_titan:
	-@(make test_titan_start)
	-@(make test_titan_restart)

test_titan_start:
	@echo "test_titan_compile..." > test_titan.diff
	make test_titan_compile
	@echo "test_titan_rundir..." >> test_titan.diff
	make test_titan_rundir
	@echo "test_titan_run..." >> test_titan.diff
	make test_titan_run
	@echo "test_titan_check..." >> test_titan.diff
	make test_titan_check

test_titan_compile:
	./Config.pl -u=Titan -e=MhdTitan -g=6,6,6,1000,200
	make
	make PIDL

test_titan_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/TITAN/PARAM.in .; \
		tar xzf Param/TITAN/TitanInput.tgz
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_titan_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf TitanTest; ./PostProc.pl -M -o TitanTest

test_titan_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-15 \
		Param/TITAN/TestOutput/log_n000001.log \
		${TESTDIR}/TitanTest/GM/log_n000001.log > test_titan.diff
	ls -l test_titan.diff

test_titan_restart:
	@echo "test_titan_restart_save..." > test_titan_restart.diff
	make test_titan_restart_save
	@echo "test_titan_restart_read..." >> test_titan_restart.diff
	make test_titan_restart_read
	@echo "test_titan_restart_check..." >> test_titan_restart.diff
	make test_titan_restart_check

test_titan_restart_save:
	cd ${TESTDIR}; cp Param/TITAN/PARAM.in.restartsave PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf TitanTest/RestartSave RESTART_titan
	cd ${TESTDIR}; ./PostProc.pl -M -o TitanTest/RestartSave

test_titan_restart_read:
	cd ${TESTDIR}; cp Param/TITAN/PARAM.in.restartread PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ./Restart.pl -i TitanTest/RestartSave/RESTART
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf TitanTest/RestartRead
	cd ${TESTDIR}; ./PostProc.pl -M -o TitanTest/RestartRead

test_titan_restart_check:
	cd ${TESTDIR}/TitanTest; \
		cp RestartSave/GM/log_n000001.log log_all.log; \
		tail -25 RestartRead/GM/log_n000026.log >> log_all.log
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-15 \
		Param/TITAN/TestOutput/log_n000001.log \
		${TESTDIR}/TitanTest/log_all.log > test_titan_restart.diff
	ls -l test_titan*.diff

### TESTS FOR MODELING MARS ###

test_mars:
	-@(make test_mars_start)

test_mars_start:
	@echo "test_mars_compile..." > test_mars.diff
	make test_mars_compile
	@echo "test_mars_rundir..." >> test_mars.diff
	make test_mars_rundir
	@echo "test_mars_run..." >> test_mars.diff
	make test_mars_run
	@echo "test_mars_check..." >> test_mars.diff
	make test_mars_check

test_mars_compile:
	./Config.pl -u=Mars -e=MhdMars -g=6,6,6,1000,200
	make
	make PIDL

test_mars_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/MARS/PARAM.in .; \
		cp Param/MARS/marsmgsp.txt .
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_mars_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf MarsTest; ./PostProc.pl -M -o MarsTest

test_mars_check:
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		Param/MARS/TestOutput/log_n000001.log \
		${TESTDIR}/MarsTest/GM/log_n000001.log > test_mars.diff
	ls -l test_mars.diff

### TESTS FOR MODELING MARSFLUIDS ###

test_marsfluids:
	-@(make test_marsfluids_start)
	-@(make test_marsfluids_restart)

test_marsfluids_start:
	@echo "test_marsfluids_compile..." > test_marsfluids.diff
	make test_marsfluids_compile
	@echo "test_marsfluids_rundir..." >> test_marsfluids.diff
	make test_marsfluids_rundir
	@echo "test_marsfluids_run..." >> test_marsfluids.diff
	make test_marsfluids_run
	@echo "test_marsfluids_check..." >> test_marsfluids.diff
	make test_marsfluids_check

test_marsfluids_compile:
	./Config.pl -u=MarsFluids -e=MhdMarsFluids -g=6,6,6,1000,200
	make
	make PIDL

test_marsfluids_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/MARSFLUIDS/PARAM.in .
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_marsfluids_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf MarsFluidsTest; ./PostProc.pl -M -o MarsFluidsTest

test_marsfluids_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-15 \
		Param/MARSFLUIDS/TestOutput/log_n000001.log \
		${TESTDIR}/MarsFluidsTest/GM/log_n000001.log > test_marsfluids.diff
	ls -l test_marsfluids.diff

test_marsfluids_restart:
	@echo "test_marsfluids_restart_save..." > test_marsfluids_restart.diff
	make test_marsfluids_restart_save
	@echo "test_marsfluids_restart_read..." >> test_marsfluids_restart.diff
	make test_marsfluids_restart_read
	@echo "test_marsfluids_restart_check..." >> test_marsfluids_restart.diff
	make test_marsfluids_restart_check


test_marsfluids_restart_save:
	cd ${TESTDIR}; cp Param/MARSFLUIDS/PARAM.in.restartsave PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; sleep 1; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf MarsFluidsTest/RestartSave RESTART_marsfluids
	cd ${TESTDIR}; ./PostProc.pl -M -o MarsFluidsTest/RestartSave

test_marsfluids_restart_read:
	cd ${TESTDIR}; cp Param/MARSFLUIDS/PARAM.in.restartread PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ./Restart.pl -i MarsFluidsTest/RestartSave/RESTART
	cd ${TESTDIR}; sleep 1; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf MarsFluidsTest/RestartRead
	cd ${TESTDIR}; ./PostProc.pl -M -o MarsFluidsTest/RestartRead

test_marsfluids_restart_check:
	cd ${TESTDIR}/MarsFluidsTest; \
		cp RestartSave/GM/log_n000001.log log_all.log; \
		tail -10 RestartRead/GM/log_n000011.log >> log_all.log
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-15 \
		Param/MARSFLUIDS/TestOutput/log_n000001.log \
		${TESTDIR}/MarsFluidsTest/log_all.log > test_marsfluids_restart.diff
	ls -l test_marsfluids*.diff


### TESTS FOR MODELING VENUS ###

test_venus:
	-@(make test_venus_start)
	-@(make test_venus_restart)

test_venus_start:
	@echo "test_venus_compile..." > test_venus.diff
	make test_venus_compile
	@echo "test_venus_rundir..." >> test_venus.diff
	make test_venus_rundir
	@echo "test_venus_run..." >> test_venus.diff
	make test_venus_run
	@echo "test_venus_check..." >> test_venus.diff
	make test_venus_check

test_venus_compile:
	./Config.pl -u=Venus -e=MhdMars -g=6,6,6,1000,200
	make
	make PIDL

test_venus_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/VENUS/PARAM.in .; \
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_venus_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf VenusTest; ./PostProc.pl -M -o VenusTest

test_venus_check:
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 -a=1e-17 \
		Param/VENUS/TestOutput/log_n000001.log \
		${TESTDIR}/VenusTest/GM/log_n000001.log > test_venus.diff
	ls -l test_venus.diff

test_venus_restart:
	@echo "test_venus_restart_save..." > test_venus_restart.diff
	make test_venus_restart_save
	@echo "test_venus_restart_read..." >> test_venus_restart.diff
	make test_venus_restart_read
	@echo "test_venus_restart_check..." >> test_venus_restart.diff
	make test_venus_restart_check

test_venus_restart_save:
	cd ${TESTDIR}; cp Param/VENUS/PARAM.in.restartsave PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf VenusTest/RestartSave RESTART_venus
	cd ${TESTDIR}; ./PostProc.pl -M -o VenusTest/RestartSave

test_venus_restart_read:
	cd ${TESTDIR}; cp Param/VENUS/PARAM.in.restartread PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in
	cd ${TESTDIR}; ./Restart.pl -i VenusTest/RestartSave/RESTART
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf VenusTest/RestartRead
	cd ${TESTDIR}; ./PostProc.pl -M -o VenusTest/RestartRead

test_venus_restart_check:
	cd ${TESTDIR}/VenusTest; \
		cp RestartSave/GM/log_n000001.log log_all.log; \
		tail -25 RestartRead/GM/log_n000026.log >> log_all.log
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-15 \
		Param/VENUS/TestOutput/log_n000001.log \
		${TESTDIR}/VenusTest/log_all.log > test_venus_restart.diff
	ls -l test_venus*.diff

### TESTS FOR MODELING SATURN ###

test_saturn:
	-@(make test_saturn_start)

test_saturn_start:
	@echo "test_saturn_compile..." > test_saturn.diff
	make test_saturn_compile
	@echo "test_saturn_rundir..." >> test_saturn.diff
	make test_saturn_rundir
	@echo "test_saturn_run..." >> test_saturn.diff
	make test_saturn_run
	@echo "test_saturn_check..." >> test_saturn.diff
	make test_saturn_check

test_saturn_compile:
	./Config.pl -u=Saturn -e=MhdHyp -g=8,8,8,720,1
	make
	make PIDL

test_saturn_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/SATURN/PARAM.in .; \
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_saturn_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf RESULTS; ./PostProc.pl -M RESULTS

test_saturn_check:
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 -a=1e-17 \
		Param/SATURN/TestOutput/log_n000001.log \
		${TESTDIR}/RESULTS/GM/log_n000001.log > test_saturn.diff
	ls -l test_saturn.diff

### TESTS FOR MODELING COMET6SP ###

test_comet:
	@echo "test_comet_compile..." > test_comet.diff
	make test_comet_compile
	@echo "test_comet_rundir..." >> test_comet.diff
	make test_comet_rundir
	@echo "test_comet_run..." >> test_comet.diff
	make test_comet_run
	@echo "test_comet_check..." >> test_comet.diff
	make test_comet_check

test_comet_compile:
	./Config.pl -u=Comet6Sp -e=MhdComet -g=8,8,8,600,100
	make
	make PIDL

test_comet_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/COMET/PARAM.in .; \
		#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_comet_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; rm -rf CometTest; ./PostProc.pl -M -o CometTest

test_comet_check:
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 -a=1e-10 \
		Param/COMET/TestOutput/log_n000001.log \
		${TESTDIR}/CometTest/GM/log_n000001.log > test_comet.diff
	ls -l test_comet.diff

### TESTS FOR MODELING EARTH WITH SPHERICAL GRID ###

test_earthsph:
	-@(make test_earthsph_start)

test_earthsph_start:
	@echo "test_earthsph_compile..." > test_earthsph.diff
	make test_earthsph_compile
	@echo "test_earthsph_rundir..." >> test_earthsph.diff
	make test_earthsph_rundir
	@echo "test_earthsph_run..." >> test_earthsph.diff
	make test_earthsph_run
	@echo "test_earthsph_check..." >> test_earthsph.diff
	make test_earthsph_check

test_earthsph_compile:
	./Config.pl -e=Mhd -u=Default -g=8,8,8,600,300
	make

test_earthsph_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/EARTH/PARAM.in.spherical PARAM.in; \
		cp Param/EARTH/imf19980504.dat .
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_earthsph_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}/GM; ./pTEC g
	cd ${TESTDIR}; rm -rf RESULTS; ./PostProc.pl -M RESULTS

test_earthsph_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		Param/EARTH/TestOutput/SPHlog_n000001.log \
		${TESTDIR}/RESULTS/GM/log_n000001.log > test_earthsph.diff)
	ls -l test_earthsph.diff

### TESTS FOR CORRECT 2 BODY PLOT FILES ###

test_2bodyplot:
	@echo "test_2bodyplot_compile..." > test_2bodyplot.diff
	make test_2bodyplot_compile
	@echo "test_2bodyplot_rundir..." >> test_2bodyplot.diff
	make test_2bodyplot_rundir
	@echo "test_2bodyplot_run..." >> test_2bodyplot.diff
	make test_2bodyplot_run
	@echo "test_2bodyplot_check..." >> test_2bodyplot.diff
	make test_2bodyplot_check

test_2bodyplot_compile:
	./Config.pl -e=Mhd -u=Default -g=8,8,8,600,300
	make
	make PIDL

test_2bodyplot_rundir: test_rundir
	cd ${TESTDIR}; \
		cp Param/2BODYPLOT/PARAM.in PARAM.in
	#./TestParam.pl -n=1 ${TESTDIR}/PARAM.in

test_2bodyplot_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}/GM; ./pTEC g
	cd ${TESTDIR}; rm -rf RESULTS; ./PostProc.pl -g -M RESULTS

# Sort the files by numerical values of the first two columns (coordinates)
SORT = sort -k1 -k2 -k3 -n

test_2bodyplot_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 -a=1e-6 \
		Param/2BODYPLOT/TestOutput/REFlog_n000001.log \
		${TESTDIR}/RESULTS/GM/log_n000001.log > test_2bodyplot.diff)
	gunzip -c Param/2BODYPLOT/TestOutput/REFy*.out.gz | ${SORT} \
		> ${TESTDIR}/RESULTS/GM/ref_y=0.out
	gunzip -c Param/2BODYPLOT/TestOutput/REFy*.dat.gz | ${SORT} \
		> ${TESTDIR}/RESULTS/GM/ref_y=0.dat
	${SORT} ${TESTDIR}/RESULTS/GM/y=0_ful_*9_*.out \
		> ${TESTDIR}/RESULTS/GM/y=0.out
	gunzip -c ${TESTDIR}/RESULTS/GM/y=0_ful_*9_*.dat.gz | ${SORT} \
		| grep -v AUXDATA \
		> ${TESTDIR}/RESULTS/GM/y=0.dat
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 -a=1e-6\
		${TESTDIR}/RESULTS/GM/ref_y=0.out \
		${TESTDIR}/RESULTS/GM/y=0.out >> test_2bodyplot.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 -a=1e-6\
		${TESTDIR}/RESULTS/GM/ref_y=0.dat \
		${TESTDIR}/RESULTS/GM/y=0.dat >> test_2bodyplot.diff)
	ls -l test_2bodyplot.diff


### ALFVEN WAVE TEST FOR SINGLE FLUID MHD WITH ANISOTROPIC PRESSURE ###

test_anisotropic:
	@echo "test_anisotropic_compile..." > test_anisotropic.diff
	make test_anisotropic_compile
	@echo "test_anisotropic_rundir..." >> test_anisotropic.diff
	make test_anisotropic_rundir
	@echo "test_anisotropic_run..." >> test_anisotropic.diff
	make test_anisotropic_run
	@echo "test_anisotropic_check..." >> test_anisotropic.diff
	make test_anisotropic_check

test_anisotropic_compile:
	./Config.pl -u=Waves -e=MhdAnisoP -g=100,2,2,100,1
	make
	make PIDL

test_anisotropic_rundir: test_rundir
	cd ${TESTDIR}; cp Param/ANISOPRESSURE/PARAM.in.Alfven PARAM.in

test_anisotropic_run:
	cd ${TESTDIR}; ${MPIRUN} ./BATSRUS.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl RESULT

test_anisotropic_check:
	${SCRIPTDIR}/DiffNum.pl -t -r=1e-5 -a=1e-12 \
	  Param/ANISOPRESSURE/TestOutput/alfven_ref.out \
	  ${TESTDIR}/RESULT/GM/cut_*t03*.out > test_anisotropic.diff
	ls -l test_anisotropic.diff
