#!/bin/csh

if($1 == 'help' || $1 == '-h' || $1 == '-help')then
   echo "Compare covariant configuration with a similar Cartesian configuration."
   echo "The results will be in run_covariant and run_covarcheck."
   echo "The comparison is done with TestCompare.pl and saved into compare.txt"
   echo "Usage:"
   echo ""
   echo "TestCovariant.pl [some test runs]"
   echo ""
   echo "where the argument is a test run typically using TestBatsrus.pl or TestSuite.pl."
   echo "The default test is running TestBatsrus.pl without arguments"
   echo "Examples:"
   echo ""
   echo "TestCovariant                          # do default test"
   echo "TestCovariant TestBatsrus.pl -ta       # do another test"
   echo "TestCovariant TestSuite.pl func        # do test suite"
   echo "TestCovariant make                     # just compile"
   echo "TestCovariant echo Configuration done  # just configure"
   exit
endif

if($1 == '')then
   set test='TestBatsrus.pl'
else
   set test="$*"
endif

rm -rf COVARIANT; make covariant_src;
cd COVARIANT; $test; cd ..

rm -rf COVARCHECK; make covarcheck_src;
cd COVARCHECK; $test; cd ..

rm -f compare.txt
TestCompare.pl -o=1e-14 COVARIANT/run COVARCHECK/run >& compare.txt
cat compare.txt

