#!/bin/sh
#^CFG COPYRIGHT UM

echo ' '
echo 'Proccessing *.dat files'
echo ' '

dir='.'
for i in `ls $dir/*.dat`
do
  echo '    processing' $i
  /usr/contrib/bin/preplot ${i}
done

echo 'ls -l'
echo ' '
ls -l

