#!/bin/sh
#  Copyright (C) 2002 Regents of the University of Michigan, portions used with permission 
#  For more information, see http://csem.engin.umich.edu/tools/swmf

echo ' '
echo 'Proccessing *.dat files'
echo ' '

dir='.'
for i in `ls $dir/*.dat`
do
  echo '    processing' $i
  /usr/contrib/bin/preplot ${i}
  /bin/rm ${i}
done

echo 'ls -l'
echo ' '
ls -l

