# Local Makefile.def

localdefault: help # default target

SCRIPTDIR = ${GMDIR}/share/Scripts
LIBDIR    = ${GMDIR}/src
RUNDIR    = ${GMDIR}/run
BINDIR    = ${GMDIR}/src
SHAREDIR  = ${GMDIR}/share/Library/src
MODDIR    = ${SHAREDIR}    # MODDIR is still used in makefiles !!!

TIMINGDIR = util/TIMING/src
#TIMINGDIR = util/TIMING/srcEmpty
