# Local Makefile.def

localdefault: help # default target

DIR       = ${GMDIR}
SCRIPTDIR = ${GMDIR}/share/Scripts
LIBDIR    = ${GMDIR}/src
RUNDIR    = ${GMDIR}/run
BINDIR    = ${GMDIR}/src
SHAREDIR  = ${GMDIR}/share/Library/src

TIMINGDIR = ${GMDIR}/util/TIMING/src
#TIMINGDIR = ${GMDIR}/util/TIMING/srcEmpty
EMPIRICALEEDIR = ${GMDIR}/util/EMPIRICAL/srcEE
